- name: password
  pattern: pass(word?)[[:blank:]]*[=:][[:blank:]]*.+
- name: password
  pattern: pwd[[:blank:]]*[=:][[:blank:]]*.+
- name: username
  pattern: username[[:blank:]]*[=:][[:blank:]]*.+
- name: username
  pattern: uname[[:blank:]]*[=:][[:blank:]]*.+
- name: RSA private key
  pattern: BEGIN RSA PRIVATE KEY
- name: key value
  pattern: _KEY
- name: token value
  pattern: _TOKEN
- name: auth token
  pattern: _auth
- name: API key
  pattern: APIKEY
- name: access key
  pattern: ACCESSKEY
- name: session token
  pattern: SESSIONTOKEN
- name: SSL certificate
  pattern: BEGIN CERTIFICATE
- name: IPv4 address
  pattern: \([[:digit:]]{1,3}[\.]\){3}[[:digit:]]{1,3}
- name: IPv6 address
  pattern: [0-9a-f]{1,4}((:[0-9a-f]{1,4}){0,6}::[0-9a-f]{0,4}|(:[0-9a-f]{1,4}){7})
- name: JDBC database configuration
  pattern: jdbc:[[:alnum:]]+://[^\s]+
- name: database configuration
  pattern: ://[[:alnum:]]*:
- name: email address
  pattern: @[A-Z0-9-]+\.[A-Z0-9-\.]+
